name: nightly
on:
  # run this workflow every night at 3am
  schedule:
    - cron: '0 3 * * *'
  # or when the user triggers it from GitHub Actions page
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Node version
        run: node -v
      # https://github.com/cypress-io/github-action
      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start-18
          wait-on: 'http://127.0.0.1:3000'
